name: Build and Push image to DockerHub

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  test_go:
    name: Run go tests
    runs-on: medium
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
